name: 构建Python项目

on:
  push:
    branches:
      - main

jobs:
  build-python-projects:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout代码
      uses: actions/checkout@v3

    - name: 更新系统
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y

    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: 安装jq
      run: sudo apt-get install -y jq

    - name: 安装PyInstaller所需的系统包
      run: sudo apt-get install -y patchelf libglu1-mesa

    - name: 查找未构建的项目并构建它们
      run: |
        set -e
        mkdir -p dist
        for project_dir in script/*/; do
          project_name=$(basename "$project_dir")
          dist_file="${{ github.workspace }}/dist/${project_name}.tar.gz"
          if [ ! -f "$dist_file" ]; then
            cd "$project_dir"
            echo "当前目录结构:"
            ls -la
            
            # 解析 set.json 获取配置信息
            packaging_platform=$(jq -r '.packaging_platform // "pyinstaller"' set.json)
            python_version=$(jq -r '.python_version // "3.8"' set.json)
            python_dependencies=$(jq -r '.python_dependencies[] // empty' set.json)
            command=$(jq -r '.command // ""' set.json)

            # 更新Python环境到指定版本
            if [[ -n "$python_version" ]]; then
              echo "将Python版本设置为 $python_version"
              python -m pip install --upgrade pip
              echo "python-version=$python_version" >> $GITHUB_ENV
            fi

            # 安装项目依赖
            for dep in $python_dependencies; do
              pip install "$dep"
            done

            # 根据打包平台进行操作
            if [ "$packaging_platform" == "pyinstaller" ]; then
              pip install pyinstaller
              if [ -n "$command" ]; then
                eval "$command" || { echo "执行命令失败"; exit 1; }
              else
                echo "未提供完整的命令，构建失败。"
                exit 1
              fi
            
              # 将生成的可执行文件及相关资源打包
              if [[ -d "dist" && "$(ls -A dist)" ]]; then
                tar -czvf "$dist_file" -C dist .
              else
                echo "未找到要打包的文件。"
                exit 1
              fi
            else
              echo "不支持的打包平台: $packaging_platform"
              exit 1
            fi
          else 
            echo "$project_name 已构建，跳过。"
          fi
        done

    - name: 添加和提交更改
      run: |
        git config --global user.name "FireStar0507"
        git config --global user.email "18064625480@163.com"
        git add dist
        git commit -m "自动构建和更新 dist 文件夹" || true
        git push origin main 
